// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qugS1u_MrlzX1kC8c53S6TKacgmd1k8',
    appId: '1:238575568272:android:0cb8a02020f1dc997d9f15',
    messagingSenderId: '238575568272',
    projectId: 'hipal-dc573',
    storageBucket: 'hipal-dc573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-U4QLxR9KZvpagvnI9paGTlRQfUnisgI',
    appId: '1:238575568272:ios:9db5c1f28dffd3397d9f15',
    messagingSenderId: '238575568272',
    projectId: 'hipal-dc573',
    storageBucket: 'hipal-dc573.appspot.com',
    iosClientId: '238575568272-blmnafa48gu4aencp7d16fojt8cdspu3.apps.googleusercontent.com',
    iosBundleId: 'com.hipal.co.hipal',
  );
}
